# .github/workflows/deploy-ec2-ssm.yml
name: Deploy to EC2 with SSM and Docker Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to latest version compatible with Node 20
        with:
          fetch-depth: 0  # Fetch full history to avoid Git-related errors

      # 2. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3  # Updated to latest version compatible with Node 20
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 3. Build and push Docker images to Docker Hub
      - name: Build and push Docker images
        run: |
          # Build frontend and backend images
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest ./frontend
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest ./backend

          # Push images to Docker Hub
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest

      # 4. Configure AWS CLI
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 5. Use SSM to deploy on EC2
      - name: Deploy Docker containers via SSM
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.AWS_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy Docker containers" \
            --parameters 'commands=[
              "echo $DOCKER_HUB_ACCESS_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin",
              "docker pull $DOCKER_HUB_USERNAME/frontend:latest",
              "docker pull $DOCKER_HUB_USERNAME/backend:latest",
              "docker stop frontend || true && docker rm frontend || true",
              "docker stop backend || true && docker rm backend || true",
              "docker run -d --name frontend -p 3000:80 $DOCKER_HUB_USERNAME/frontend:latest",
              "docker run -d --name backend -p 5000:5000 $DOCKER_HUB_USERNAME/backend:latest"
            ]'
